ALTER TABLE EDG_EDGE ADD EDG_NAME_TMP varchar(max)
go
open symmetric key EDGKey decryption by certificate CertPMap  with password = 'FormClosedEventArgs' 
update EDG_EDGE set EDG_NAME_TMP = convert(varchar(max),decryptbykey(EDG_NAME_ENC)) 
go

drop SYMMETRIC KEY EDGKey 
go 
drop CERTIFICATE CertPMap 
go
drop MASTER KEY 
go 

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'PMapPtx01' 
go
CREATE CERTIFICATE CertPMap ENCRYPTION BY PASSWORD = 'FormClosedEventArgs01' WITH SUBJECT = 'PMapPtx01' 
go
CREATE SYMMETRIC KEY EDGKey WITH ALGORITHM = TRIPLE_DES ENCRYPTION BY CERTIFICATE CertPMap
go
OPEN SYMMETRIC KEY EDGKey DECRYPTION BY CERTIFICATE CertPMap WITH PASSWORD = 'FormClosedEventArgs01' 
Update EDG_EDGE SET EDG_NAME_ENC = ENCRYPTBYKEY(KEY_GUID('EDGKey'),EDG_NAME_TMP) 
go
ALTER TABLE EDG_EDGE DROP COLUMN EDG_NAME_TMP
go