select DSTNEW.NOD_ID_FROM, DSTNEW.NOD_ID_TO,
DSTNEW.DST_DISTANCE as NDIST, DSTOLD.DST_DISTANCE as ODIST,
DSTNEW.DST_TIME as NTIME, DSTOLD.DST_TIME OTIME, DSTOLD.DST_PATH
from CT_DREHER.dbo.DST_DISTANCE DSTNEW
inner join CT_DREHER_ORI.dbo.DST_DISTANCE DSTOLD on DSTNEW.NOD_ID_FROM = DSTOLD.NOD_ID_FROM and  DSTNEW.NOD_ID_TO = DSTOLD.NOD_ID_TO and DSTNEW.SPP_ID = DSTOLD.SPP_ID
