//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMapCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMapCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _8 {
            get {
                object obj = ResourceManager.GetObject("_8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_black {
            get {
                object obj = ResourceManager.GetObject("bullet_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_blue {
            get {
                object obj = ResourceManager.GetObject("bullet_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply,&quot;Alkalmaz&quot;
        ///CalcButtonBack,&quot;Vissza&quot;
        ///CalcButtonC,&quot;C&quot;
        ///CalcButtonCE,&quot;CE&quot;
        ///CalcButtonMC,&quot;MC&quot;
        ///CalcButtonMR,&quot;MR&quot;
        ///CalcButtonMS,&quot;MS&quot;
        ///CalcButtonMx,&quot;M+&quot;
        ///StringId.CalcButtonSqrt,&quot;Sqr&quot;
        ///CalcError,&quot;Hiba&quot;
        ///Cancel,&quot;Mégsem&quot;
        ///CaptionError,&quot;Hiba&quot;
        ///CheckChecked,&quot;Ellenőrzött&quot;
        ///CheckIndeterminate,&quot;Eldöntetlen&quot;
        ///CheckUnchecked,&quot;Ellenőrizetlen&quot;
        ///ColorTabCustom,&quot;Saját&quot;
        ///ColorTabSystem,&quot;Rendszer&quot;
        ///ColorTabWeb,&quot;Web&quot;
        ///ContainerAccessibleEditName,
        ///DataEmpty,&quot;Üres&quot;
        ///DateEditClear,&quot;Törlés&quot;
        ///DateEditToday,&quot;Mai nap&quot;
        ///FilterCl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string editorloc_hu {
            get {
                return ResourceManager.GetString("editorloc_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag_blue {
            get {
                object obj = ResourceManager.GetObject("flag_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag1 {
            get {
                object obj = ResourceManager.GetObject("flag1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag2 {
            get {
                object obj = ResourceManager.GetObject("Flag2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag3 {
            get {
                object obj = ResourceManager.GetObject("Flag3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardViewCaptionFormat,
        ///CardViewNewCard,
        ///CardViewQuickCustomizationButton,
        ///CardViewQuickCustomizationButtonFilter,
        ///CardViewQuickCustomizationButtonSort,
        ///GridStringId.ColumnViewExceptionMessage,
        ///CustomFilterDialog2FieldCheck,&quot;Mező&quot;
        ///CustomFilterDialogCancelButton,&quot;Mégsem&quot;
        ///CustomFilterDialogCaption,&quot;Saját szűrő beállítása&quot;
        ///CustomFilterDialogClearFilter,&quot;Szűrő törlése&quot;
        ///CustomFilterDialogConditionBlanks,&quot;üres&quot;
        ///CustomFilterDialogConditionEQU,&quot;egyenlő&quot;
        ///CustomFilterDialogConditionGT,&quot;nagyobb, mint&quot;
        ///Cust [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gridloc_hu {
            get {
                return ResourceManager.GetString("gridloc_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker {
            get {
                object obj = ResourceManager.GetObject("marker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button_Cancel,&quot;Mégsem&quot;
        ///Button_Ok,&quot;Ok&quot;
        ///Button_Help,&quot;Súgó&quot;
        ///Button_Apply,&quot;Alkalmaz&quot;
        ///PreviewForm_Caption,&quot;Nyomtatási kép&quot;
        ///TB_TTip_Customize,&quot;Testreszabás&quot;
        ///TB_TTip_Print,&quot;Nyomtatás&quot;
        ///TB_TTip_PrintDirect,&quot;Közvetlen nyomtatás&quot;
        ///TB_TTip_PageSetup,&quot;Oldalbeállítások&quot;
        ///TB_TTip_Magnifier,&quot;Nagyító&quot;
        ///TB_TTip_ZoomIn,&quot;Nagyítás&quot;
        ///TB_TTip_ZoomOut,&quot;Kicsinyítés&quot;
        ///TB_TTip_Zoom,&quot;Nagyítás&quot;
        ///TB_TTip_Search,&quot;Keresés&quot;
        ///TB_TTip_FirstPage,&quot;Első oldal&quot;
        ///TB_TTip_PreviousPage,&quot;Előző oldal&quot;
        ///TB_TTip_NextPage,&quot;Következő oldal&quot;
        ///TB_TT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ppreviewloc_hu {
            get {
                return ResourceManager.GetString("ppreviewloc_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shadow50 {
            get {
                object obj = ResourceManager.GetObject("shadow50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
