name: Run tests on pull request

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Run tests
        run: dotnet test
